<?php

namespace MMBundle\Repository;

/**
 * AttedanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttedanceRepository extends \Doctrine\ORM\EntityRepository
{
}
