<?php

namespace MMBundle\Repository;

/**
 * ContractorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractorRepository extends \Doctrine\ORM\EntityRepository
{
}
