<?php

namespace MMBundle\Repository;

/**
 * EquimpmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquimpmentRepository extends \Doctrine\ORM\EntityRepository
{
}
