<?php

namespace MMBundle\Repository;

/**
 * PurchaseInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
