<?php

namespace MMBundle\Repository;

/**
 * SaleInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($form) {
        $qb = $this->createQueryBuilder('e');



        if(!empty($form->get('contractorId')->getData())) {
            $qb->orWhere('e.contractorId = :ctr')
                ->setParameter('ctr', $form->get('contractorId')->getData());
        }

        if(!empty($form->get('taxId')->getData())) {
            $qb->orWhere('e.taxId = :tax')
                ->setParameter('tax', $form->get('taxId')->getData());
        }
        if(!empty($form->get('number')->getData())) {
            $qb->orWhere('e.number = :num')
                ->setParameter('num', $form->get('number')->getData());
        }

        return $qb->getQuery()->getResult();
    }
    public function filter($form) {
        $qb = $this->createQueryBuilder('d');
        if(!empty($form->get('data')->getData())) {
            $qb->orWhere('d.data = :data')
                ->setParameter('data', $form->get('data')->getData());
        }
        return $qb->getQuery();
    }
}
