<?php

namespace MMBundle\Repository;

/**
 * SaleInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
