MMBundle\Entity\License:
    type: entity
    table: null
    repositoryClass: MMBundle\Repository\LicenseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: string
            length: 255
        name:
            type: string
            length: 255
        serialkey:
            type: string
            length: 255
        datepurchase:
            type: date
        datesupport:
            type: date
        validity:
            type: date
        technicalcondition:
            type: string
            length: 255
        comments:
            type: string
            length: 255
    lifecycleCallbacks: {  }
